name: ${PROJECT_NAME}-dev

services:
  budget-api:
    build:
      target: dev
    volumes:
      - ../budget:/app/budget
      - ../shared:/app/shared
    env_file:
      - ./.env
      - ./.env.dev
