name: ${PROJECT_NAME}
services:

  # identity-api:
  #   build:
  #     context: ../identity
  #   container_name: identity-api
  #   depends_on:
  #     - identity-api-db
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - identity-api_app_data:/app
  #   env_file:
  #     - ./.env
  #   networks:
  #     - backend
  #     - identity-api
  #   healthcheck:
  #     test: ["CMD", "curl", "http://localhost:8080/api/v1/users"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #     start_period: 10s
  # identity-api-db:
  #   image: mysql:latest
  #   container_name: identity-api-db
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${IDENTITY_API_MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${IDENTITY_API_DB_DATABASE}
  #     MYSQL_USER: ${IDENTITY_API_DB_USER}
  #     MYSQL_PASSWORD: ${IDENTITY_API_DB_PASSWORD}
  #   ports:
  #     - "${IDENTITY_API_DB_PORT}:3306"
  #   volumes:
  #     - identity-api_db_data:/var/lib/mysql
  #   networks:
  #     - identity-api

  budget-api:
    build:
      context: ../budget
    container_name: budget-api
    depends_on:
      - budget-api-db
      # - identity-api
    ports:
      - "8080:8080"
    volumes:
      - budget-api_app_data:/app
    env_file:
      - ./.env
    networks:
      - backend
      - budget-api
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/api/v1/users"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
  budget-api-db:
    image: mysql:latest
    container_name: budget-api-db
    environment:
      MYSQL_ROOT_PASSWORD: ${BUDGET_API_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${BUDGET_API_DB_DATABASE}
      MYSQL_USER: ${BUDGET_API_DB_USER}
      MYSQL_PASSWORD: ${BUDGET_API_DB_PASSWORD}
    ports:
      - "${BUDGET_API_DB_PORT}:3306"
    volumes:
      - budget-api_db_data:/var/lib/mysql
    networks:
      - budget-api 

  # migrate:
  #   build:
  #     context: ../migrate
  #    profiles:
  #    - test

volumes:
  budget-api_app_data:
  budget-api_db_data:
  identity-api_app_data:
  identity-api_db_data:

networks:
  identity-api:
  budget-api:
  backend: