name: ${PROJECT_NAME}-dev

services:
  identity-api:
    build:
      target: dev
    volumes:
      - ../identity:/app/identity
      - ../shared:/app/shared
    env_file:
      - ./.env
      - ./.env.dev

  budget-api:
    build:
      target: dev
    volumes:
      - ../budget:/app/budget
      - ../shared:/app/shared
    env_file:
      - ./.env
      - ./.env.dev
