services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - "3306"

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki/:/etc/loki/
    expose:
      - "3100"

  alloy:
    image: grafana/alloy:latest
    command: --config.file=/etc/alloy/config.alloy
    volumes:
      - ./config/alloy:/etc/alloy
    depends_on:
      - loki

  grafana:
    image: grafana/grafana-oss:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    expose:
      - "3000"
    depends_on:
      - loki

volumes:
  mysql_data:
  grafana_data:
