services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  budget-api:
    build:
      context: ../../budget-api
      dockerfile: Dockerfile
      target: local
    env_file:
      - ../.env
      - ./.env.local
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    working_dir: /budget-api
    volumes:
      - ../../budget-api:/budget-api
    networks:
      - backend
    command: air cmd/api/main.go -c .air.toml

volumes:
  mysql_data:

networks:
  backend: