import type { Locale } from "@/lib/i18n"

const en = {
  overview: "Overview", expenses: "Expenses", plan: "Monthly plan", savings: "Savings",
  remaining: "Fun money left", starting: "Starting allowance", reserved: "Reserved categories", buffer: "Protected buffer",
  addExpense: "Add expense", spendSavings: "Spend from savings", spendCategory: "Add expense here",
  emptyCategories: "Add categories in your monthly plan to organize purchases.",
  emptyExpenses: "No expenses yet. Add your first purchase when you're ready.",
  emptyReserves: "No category reserves. Set a monthly amount for a category in your plan.",
  setupTitle: "Set up your monthly budget", setupNote: "Enter the amounts once. Budget handles each new period automatically.",
  income: "Monthly income", fixed: "Fixed costs", monthly: "Monthly subscriptions", yearly: "Yearly subscriptions",
  savingsRate: "Monthly saving", opening: "Already saved", bufferRate: "Monthly buffer", category: "Category",
  categoryName: "Category name", addCategory: "Add category", categories: "Categories", reserve: "Monthly reserve",
  noReserve: "0 = ordinary spending", name: "Name", amount: "Amount", dueMonth: "Due month", dueDay: "Due day",
  add: "Add", remove: "Remove", savePlan: "Save for next period", startPlan: "Start my budget", cancelPending: "Cancel pending changes",
  appliesFrom: "Takes effect", applyNext: "Next period", applyCurrent: "This period", saveCurrentPlan: "Save for this period",
  applyCurrentNote: "Overwrites the running period. Earlier periods keep the plan that produced them.",
  effective: "Changes start on", pending: "A new plan is saved for next period.", current: "Current period", next: "Next period",
  forecast: "Your next 12 periods", forecastNote: "Planned allowances before purchases and any deficit carried forward. Yearly bills are deducted in full when due.",
  previewPlan: "Calculate preview", plannedFun: "Planned fun money", date: "Date", description: "Description (optional)",
  merchant: "Merchant (optional)", noMerchant: "No merchant", merchants: "Merchants",
  merchantName: "Shop or service", addMerchant: "Add merchant", publishMerchant: "For everyone",
  published: "For everyone", emptyMerchants: "No merchants of your own yet.",
  merchantsNote: "Merchants are only a label on an expense and never change your money.",
  catalogCount: "merchants ship with the app and can always be picked.",
  source: "Pay from", auto: "Use category default", fun: "Fun money", categorySource: "Category reserve", savingsSource: "Savings", bufferSource: "Buffer",
  save: "Save expense", saveAnother: "Save and add another", cancel: "Cancel", close: "Close", edit: "Edit", refund: "Refund", void: "Void",
  confirmVoid: "Void this entry? Its effect on your balances will be reversed; its history is kept.",
  confirmCancel: "Discard the pending plan and keep the current plan next period?",
  saveRefund: "Record refund", refundAmount: "Refund amount", saved: "Saved.", loading: "Loading Budget…", retry: "Retry",
  allCategories: "All categories", allSources: "All funding sources", search: "Search descriptions, merchants or categories", history: "History",
  contribution: "Added automatically each period", savingsNote: "Contributions and purchases update this balance automatically. These are budget allocations; no bank transfer is made.",
  leftoverNote: "At rollover, unused fun money and category money offset any deficit; the rest goes to Savings. Buffer stays protected.",
  deficit: "Deficit brought forward", shortfall: "Plan funding shortfall", shortfallNote: "Protected contributions could not be funded this period. Review your plan; no savings or reserves have been invented.",
  sourceBalance: "Available from this source", excess: "Not enough in this reserve", cover: "Use fun money for the difference", coverNote: "Only the difference will reduce fun money.",
  month: "Month", total: "Total", archived: "Archived", archive: "Archive", restore: "Restore", rename: "Rename", active: "Recorded", voided: "Voided",
  automaticCosts: "Already covered by your plan", automaticNote: "No need to enter these bills again. These are scheduled amounts, not bank confirmations.",
  plannedSavings: "Monthly contribution", totalSaved: "Savings available", noSavingsHistory: "Savings contributions begin automatically with your plan.",
  period: "Period", openPlan: "Edit monthly plan", from: "From", refundLabel: "Refund", previewStale: "Calculate the updated preview before saving.",
  spent: "Spent", paceNote: "The mark is today. If the bar sits left of it, you are under plan.", bufferNote: "Protected. Only spent when you say so.",
  left: "left", recent: "Recent", showAll: "Show all",
  errors: "Couldn't complete that action. Try again.",
  invalid_input: "Check the fields. Use positive amounts with at most two decimal places.", invalid_timezone: "Choose a valid timezone.",
  invalid_date: "Choose a date between the first budget period and today.", invalid_category: "Choose an available category.",
  invalid_funding: "The funding amounts must cover the expense exactly.", insufficient_funds: "This would overdraw a protected balance, possibly later in its history. Choose another source or adjust the amount.",
  category_unfunded: "This category has no funded reserve in the selected period.", category_exists: "A category with that name already exists.",
  category_reserved: "Remove this category's reserve from the plan and wait until it takes effect before archiving.",
  plan_changed: "The plan changed in another window. Reload before saving again.", plan_unaffordable: "The plan exceeds your income in at least one of the next 12 periods. Adjust the amounts.",
  opening_balance_locked: "Opening savings and timezone are fixed after setup.", request_key_reused: "That request was already used with different details. Close and reopen the form.",
  reverse_refunds_first: "Void the linked refunds before editing or voiding this expense.", refund_exceeds_expense: "The refund exceeds the amount not yet refunded.",
  date_outside_history: "That date is outside your recorded budget history.", setup_required: "Set up the monthly plan first.",
}
export type MonthlyCopy = Record<keyof typeof en, string>
const de: MonthlyCopy = {
  overview: "Übersicht", expenses: "Ausgaben", plan: "Monatsplan", savings: "Sparen",
  remaining: "Spaßbudget übrig", starting: "Budget zum Periodenstart", reserved: "Reservierte Kategorien", buffer: "Geschützter Puffer",
  addExpense: "Ausgabe erfassen", spendSavings: "Aus Erspartem bezahlen", spendCategory: "Ausgabe hier erfassen",
  emptyCategories: "Lege im Monatsplan Kategorien für deine Einkäufe an.", emptyExpenses: "Noch keine Ausgaben. Erfasse deinen ersten Einkauf, sobald du möchtest.",
  emptyReserves: "Keine Kategorien reserviert. Lege im Monatsplan einen monatlichen Betrag für eine Kategorie fest.",
  setupTitle: "Richte dein Monatsbudget ein", setupNote: "Trage die Beträge einmal ein. Budget übernimmt jede neue Periode automatisch.",
  income: "Monatliches Einkommen", fixed: "Fixkosten", monthly: "Monatliche Abos", yearly: "Jährliche Abos", savingsRate: "Monatlich sparen",
  opening: "Bereits gespart", bufferRate: "Monatlicher Puffer", category: "Kategorie", categoryName: "Kategoriename", addCategory: "Kategorie hinzufügen",
  categories: "Kategorien", reserve: "Monatlich reserviert", noReserve: "0 = normale Ausgabe", name: "Name", amount: "Betrag", dueMonth: "Fälliger Monat", dueDay: "Fälliger Tag",
  add: "Hinzufügen", remove: "Entfernen", savePlan: "Für nächste Periode speichern", startPlan: "Budget starten", cancelPending: "Geplante Änderungen verwerfen",
  appliesFrom: "Gilt ab", applyNext: "Nächste Periode", applyCurrent: "Diese Periode", saveCurrentPlan: "Für diese Periode speichern",
  applyCurrentNote: "Überschreibt die laufende Periode. Frühere Perioden behalten den Plan, der sie erzeugt hat.",
  effective: "Änderungen gelten ab", pending: "Ein neuer Plan ist für die nächste Periode gespeichert.", current: "Aktuelle Periode", next: "Nächste Periode",
  forecast: "Deine nächsten 12 Perioden", forecastNote: "Geplantes Budget vor Einkäufen und einem möglichen Minus aus der Vorperiode. Jahresabos werden bei Fälligkeit vollständig abgezogen.",
  previewPlan: "Vorschau berechnen", plannedFun: "Geplantes Spaßbudget", date: "Datum", description: "Beschreibung (optional)",
  merchant: "Händler (optional)", noMerchant: "Kein Händler", merchants: "Händler",
  merchantName: "Laden oder Dienst", addMerchant: "Händler anlegen", publishMerchant: "Für alle",
  published: "Für alle", emptyMerchants: "Noch keine eigenen Händler.",
  merchantsNote: "Der Händler ist nur eine Beschriftung der Ausgabe und ändert nie dein Geld.",
  catalogCount: "Händler sind mitgeliefert und immer auswählbar.",
  source: "Bezahlen aus", auto: "Vorgabe der Kategorie", fun: "Spaßbudget", categorySource: "Kategoriereserve", savingsSource: "Erspartem", bufferSource: "Puffer",
  save: "Ausgabe speichern", saveAnother: "Speichern und weitere erfassen", cancel: "Abbrechen", close: "Schließen", edit: "Bearbeiten", refund: "Erstattung", void: "Stornieren",
  confirmVoid: "Diesen Eintrag stornieren? Seine Wirkung auf deine Beträge wird rückgängig gemacht. Die Historie bleibt erhalten.",
  confirmCancel: "Geplante Änderungen verwerfen und den aktuellen Plan auch nächste Periode verwenden?",
  saveRefund: "Erstattung erfassen", refundAmount: "Erstatteter Betrag", saved: "Gespeichert.", loading: "Budget wird geladen…", retry: "Erneut versuchen",
  allCategories: "Alle Kategorien", allSources: "Alle Geldquellen", search: "Beschreibung, Händler oder Kategorie suchen", history: "Verlauf",
  contribution: "Wird jede Periode automatisch hinzugefügt", savingsNote: "Sparbeträge und Einkäufe aktualisieren diesen Stand automatisch. Das sind Budgetzuweisungen, keine Banküberweisungen.",
  leftoverNote: "Beim Periodenwechsel gleichen übriges Spaßbudget und Kategoriegeld ein Minus aus. Der Rest geht ins Ersparte. Der Puffer bleibt geschützt.",
  deficit: "Minus aus der Vorperiode", shortfall: "Fehlbetrag im Plan", shortfallNote: "Die geschützten Beträge konnten diese Periode nicht finanziert werden. Prüfe deinen Plan. Es wurden keine Ersparnisse oder Reserven erfunden.",
  sourceBalance: "Aus dieser Quelle verfügbar", excess: "Diese Reserve reicht nicht aus", cover: "Differenz aus dem Spaßbudget bezahlen", coverNote: "Nur die Differenz verringert dein Spaßbudget.",
  month: "Monat", total: "Gesamt", archived: "Archiviert", archive: "Archivieren", restore: "Wiederherstellen", rename: "Umbenennen", active: "Erfasst", voided: "Storniert",
  automaticCosts: "Bereits im Plan berücksichtigt", automaticNote: "Diese Rechnungen musst du nicht erneut erfassen. Es sind geplante Beträge, keine Bankbestätigungen.",
  plannedSavings: "Monatlicher Sparbetrag", totalSaved: "Verfügbares Erspartes", noSavingsHistory: "Sparbeträge beginnen automatisch mit deinem Plan.",
  period: "Periode", openPlan: "Monatsplan bearbeiten", from: "Ab", refundLabel: "Erstattung", previewStale: "Berechne vor dem Speichern die aktualisierte Vorschau.",
  spent: "Ausgegeben", paceNote: "Der Strich markiert heute. Liegt der Balken links davon, bist du unter Plan.", bufferNote: "Geschützt. Wird nur auf Ansage verwendet.",
  left: "übrig", recent: "Zuletzt", showAll: "Alle anzeigen",
  errors: "Das hat nicht geklappt. Bitte versuche es erneut.",
  invalid_input: "Prüfe die Felder. Verwende positive Beträge mit höchstens zwei Nachkommastellen.", invalid_timezone: "Wähle eine gültige Zeitzone.",
  invalid_date: "Wähle ein Datum zwischen der ersten Budgetperiode und heute.", invalid_category: "Wähle eine verfügbare Kategorie.",
  invalid_funding: "Die Geldquellen müssen die Ausgabe vollständig decken.", insufficient_funds: "Das würde einen geschützten Betrag überziehen, möglicherweise später im Verlauf. Wähle eine andere Quelle oder passe den Betrag an.",
  category_unfunded: "Diese Kategorie hat in der gewählten Periode keine finanzierte Reserve.", category_exists: "Eine Kategorie mit diesem Namen existiert bereits.",
  category_reserved: "Entferne die Reserve im Monatsplan und warte bis zur nächsten Periode, bevor du die Kategorie archivierst.",
  plan_changed: "Der Plan wurde in einem anderen Fenster geändert. Lade ihn vor dem Speichern neu.", plan_unaffordable: "Der Plan übersteigt dein Einkommen in mindestens einer der nächsten 12 Perioden. Passe die Beträge an.",
  opening_balance_locked: "Anfängliches Erspartes und Zeitzone stehen nach der Einrichtung fest.", request_key_reused: "Diese Anfrage wurde bereits mit anderen Angaben verwendet. Schließe das Formular und öffne es erneut.",
  reverse_refunds_first: "Storniere zuerst die verknüpften Erstattungen, bevor du diese Ausgabe änderst oder stornierst.", refund_exceeds_expense: "Die Erstattung übersteigt den noch nicht erstatteten Betrag.",
  date_outside_history: "Dieses Datum liegt außerhalb deiner Budgethistorie.", setup_required: "Richte zuerst den Monatsplan ein.",
}
export function monthlyCopy(locale: Locale): MonthlyCopy { return locale === "de" ? de : en }
export function monthlyError(error: unknown, copy: MonthlyCopy): string {
  if (error instanceof Error) {
    const match = Object.entries(copy).find(([key]) => key === error.message)
    if (match) return match[1]
  }
  return copy.errors
}
