name: ${PROJECT_NAME}

services:
  identity-api-db:
    image: postgres:13.22
    container_name: identity-api-db
    environment:
      POSTGRES_DB: ${IDENTITY_API_DB_DATABASE}
      POSTGRES_USER: ${IDENTITY_API_DB_USER}
      POSTGRES_PASSWORD: ${IDENTITY_API_DB_PASSWORD}
    ports:
      - "${IDENTITY_API_DB_PORT}:5432"
    volumes:
      - identity-api_db_data:/var/lib/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5