name: Module Build & Test CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [shared, budget, identity]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.0"
          cache-dependency-path: go.sum

      - name: Install dependencies
        run: cd ${{ matrix.service }} && go get ./...

      - name: Build
        run: cd ${{ matrix.service }} && go build -v ./...

      - name: Test
        run: cd ${{ matrix.service }} && go test -v ./...
